name: deploy

on:
  push:
    branches:
      - '**'

jobs:

  build:
    name: Deploy
    environment: pi-zero-production-much-important
    runs-on: ubuntu-latest
    steps:
    - name: oh yeah
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SECRET }}
        port: ${{ secrets.PORT }}
        script: whoami
